Develop
puchenicheva/coffee_maker pull request #6
Opened 2018-07-25 09:39 UTC by puchenicheva

2018-07-30 11:29 UTC, levchik requested changes
Вот как-то так. Плюс где же история про объем покрытия тестами кода?

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +    initial_weight = 0
а для чего это?

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.reservoir.current_weight == 400, ''
в тестах можно опускать второй параметр ассерта где указывается сообщение при фейле условия внутри

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.waterheater.water_temperature >=100.02
так фишка в том что она не должна быть выше 100)
вот как мы поступим:
1. сделай исправления чтобы тест проверял что вода не может больше 100 градусов быть
2. прогони его, он у тебя упадет
3. это значит что править нужно не тест а код!
4. исправь код чтобы тест прошел
5. ????
6. ПРОФИТ!!!1

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.waterheater.get_current_water_heating()
что этот тест проверяет?

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.waterheatingsensor.check_temperature_water
что этот тест проверяет? он даже метод не вызывает

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.amountcoffee.current_amount == 400
этот тест можно опустить, потому что есть тот который ниже

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.pot.current_weight == 400
лучше всего похожие штуки сравнивать по коду тестов ВЕЗДЕ так:
self.pot.current_weight == self.weight

тогда ты сможешь подставить любое значение в инициализатор
+ лучшей практикой считается использовать случайные значения для тестов, так ты свою программу прогонишь через кучу вариантов

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        self.step =10
пеп8

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +    def test_reduce_weight(self):
этот тест уже есть ниже в составе другого

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.coffeemaker.reservoir.current_weight == 390
опять же лучше высчитывать self.wight - self.step

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.coffeemaker.reservoir.current_weight == 390
короч по всему коду тестов нужно пройтись по этой теме

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        assert self.plate.warming_state
это тот же тест что и test_is_warming только обращаешься через атрибут - это лишнее, оставим только тот что ниже

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +        print()
чистим чистим чистим

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +
рер8

2018-07-30 11:29 UTC, levchik commented on tests/test_main.py
> +
пеп 8

2018-08-01 07:47 UTC, levchik requested changes

2018-08-01 07:47 UTC, levchik commented on app/main.py
> +            return 0 - x * (-1)
прикол) а почему не  return self.current_weight тогда?

2018-08-01 07:47 UTC, levchik commented on tests/test_main.py
> +    initial_weight = 0
а все-таки?

2018-08-01 07:47 UTC, levchik commented on tests/test_main.py
>      def test_reduce_weight(self):
ну так что? уберем?

2018-08-01 07:52 UTC, puchenicheva commented on app/main.py
> +            return 0 - x * (-1)
self.current_weigh нам нужно что бы было 0, но вернуть мы должны то, что оставалось, что бы это что-то добавилось в нужном объеме в pot

2018-08-02 07:57 UTC, levchik approved these changes

2018-08-02 07:58 UTC, merged